openapi: 3.0.0
info:
  title: Todo Web Application API
  description: REST API for the Todo Web Application with JWT authentication and user data isolation
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.todoapp.com
    description: Production server

paths:
  /api/{user_id}/tasks:
    get:
      summary: Retrieve all tasks for a specific user
      description: Returns a list of tasks owned by the authenticated user
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user whose tasks to retrieve
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successfully retrieved tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Invalid or missing JWT
        '403':
          description: Forbidden - User does not have access to these tasks
      security:
        - bearerAuth: []
    post:
      summary: Create a new task for a specific user
      description: Creates a new task and associates it with the authenticated user
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user creating the task
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Invalid or missing JWT
        '403':
          description: Forbidden - User does not have access to create tasks for this user_id
        '422':
          description: Unprocessable Entity - Invalid input data
      security:
        - bearerAuth: []

  /api/{user_id}/tasks/{id}:
    get:
      summary: Retrieve a specific task for a user
      description: Returns a specific task owned by the authenticated user
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user who owns the task
          schema:
            type: string
            format: uuid
        - name: id
          in: path
          required: true
          description: The ID of the task to retrieve
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successfully retrieved task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Invalid or missing JWT
        '403':
          description: Forbidden - User does not have access to this task
        '404':
          description: Task not found
      security:
        - bearerAuth: []
    put:
      summary: Update a specific task for a user
      description: Updates a specific task owned by the authenticated user
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user who owns the task
          schema:
            type: string
            format: uuid
        - name: id
          in: path
          required: true
          description: The ID of the task to update
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Invalid or missing JWT
        '403':
          description: Forbidden - User does not have access to update this task
        '404':
          description: Task not found
        '422':
          description: Unprocessable Entity - Invalid input data
      security:
        - bearerAuth: []
    delete:
      summary: Delete a specific task for a user
      description: Deletes a specific task owned by the authenticated user
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user who owns the task
          schema:
            type: string
            format: uuid
        - name: id
          in: path
          required: true
          description: The ID of the task to delete
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Task deleted successfully
        '401':
          description: Unauthorized - Invalid or missing JWT
        '403':
          description: Forbidden - User does not have access to delete this task
        '404':
          description: Task not found
      security:
        - bearerAuth: []

  /api/{user_id}/tasks/{id}/complete:
    patch:
      summary: Mark a specific task as complete/incomplete
      description: Updates the completion status of a specific task owned by the authenticated user
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user who owns the task
          schema:
            type: string
            format: uuid
        - name: id
          in: path
          required: true
          description: The ID of the task to update
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                completed:
                  type: boolean
                  description: The new completion status for the task
              required:
                - completed
      responses:
        '200':
          description: Task completion status updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Unauthorized - Invalid or missing JWT
        '403':
          description: Forbidden - User does not have access to update this task
        '404':
          description: Task not found
        '422':
          description: Unprocessable Entity - Invalid input data
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token issued by Better Auth
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the user
        email:
          type: string
          format: email
          description: User's email address
        created_at:
          type: string
          format: date-time
          description: When the user account was created
        updated_at:
          type: string
          format: date-time
          description: When the user account was last updated
      required:
        - id
        - email
        - created_at
        - updated_at
    Task:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the task
        user_id:
          type: string
          format: uuid
          description: ID of the user who owns this task
        title:
          type: string
          description: Title of the task
        description:
          type: string
          description: Optional description of the task
        completed:
          type: boolean
          description: Whether the task is completed
        created_at:
          type: string
          format: date-time
          description: When the task was created
        updated_at:
          type: string
          format: date-time
          description: When the task was last updated
      required:
        - id
        - user_id
        - title
        - completed
        - created_at
        - updated_at
    TaskCreate:
      type: object
      properties:
        title:
          type: string
          description: Title of the task (required)
          minLength: 1
        description:
          type: string
          description: Optional description of the task
        completed:
          type: boolean
          description: Initial completion status (default: false)
          default: false
      required:
        - title
    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          description: Updated title of the task
          minLength: 1
        description:
          type: string
          description: Updated description of the task
        completed:
          type: boolean
          description: Updated completion status